# Generated by Django 5.2.5 on 2025-08-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_form_customer_details_customer_blogs_achievements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='achievements',
            table='achievements',
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chat',
        ),
        migrations.AlterModelTable(
            name='customer_blogs',
            table='customer_blogs',
        ),
        migrations.AlterModelTable(
            name='customer_details',
            table='customer_details',
        ),
        migrations.AlterModelTable(
            name='customer_notification',
            table='customer_notification',
        ),
        migrations.AlterModelTable(
            name='customer_review',
            table='customer_review',
        ),
        migrations.AlterModelTable(
            name='experience_images',
            table='experience_images',
        ),
        migrations.AlterModelTable(
            name='form',
            table='form',
        ),
        migrations.AlterModelTable(
            name='form_images',
            table='form_images',
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='mentor',
        ),
        migrations.AlterModelTable(
            name='mentor_blogs',
            table='mentor_blogs',
        ),
        migrations.AlterModelTable(
            name='mentor_education',
            table='mentor_education',
        ),
        migrations.AlterModelTable(
            name='mentor_experience',
            table='mentor_experience',
        ),
        migrations.AlterModelTable(
            name='mentor_notification',
            table='mentor_notification',
        ),
        migrations.AlterModelTable(
            name='mentor_works',
            table='mentor_works',
        ),
        migrations.AlterModelTable(
            name='site_review',
            table='site_review',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='work_images',
            table='work_images',
        ),
    ]
