# Generated by Django 5.2.5 on 2025-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_user_options_alter_achievements_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_blogs',
            name='image',
            field=models.ImageField(null=True, upload_to='mentor_blogs/'),
        ),
    ]
